### ISSUE TITLE
Unable to run the Flask 123 and dist abc examples

### ISSUE THREAD

**Issue by abhishektiwari** [r3w0p/bobocep#7]
**Describe the bug**
Unable to run Flask example (`tests/postman/flask_123`) with Postman collection. Currently working on [review for JOSS submission](https://github.com/openjournals/joss-reviews/issues/5858)

```
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-02 21:57:49,813] ERROR in app: Exception on /data/int/1 [GET]
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.11.4/envs/bobocep/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/.pyenv/versions/3.11.4/envs/bobocep/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/.pyenv/versions/3.11.4/envs/bobocep/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/.pyenv/versions/3.11.4/envs/bobocep/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/Labs/joss/bobocep/app.py", line 27, in data_int
    engine.receiver.add_data(int(my_int))
    ^^^^^^
NameError: name 'engine' is not defined
```

**Expected behavior**
Postman collection should get successful response (`200`) from Flask server.

**Desktop (please complete the following information):**
—OS: Mac
—Python: `3.11.4` 

**Additional context**
Pip versions

```
attrs                     23.1.0
blinker                   1.6.2
bobocep                   1.1.0
click                     8.1.7
Flask                     3.0.0
itsdangerous              2.1.2
Jinja2                    3.1.2
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
MarkupSafe                2.1.3
pip                       23.1.2
pycryptodome              3.18.0
referencing               0.30.2
rpds-py                   0.10.3
setuptools                65.5.0
Werkzeug                  3.0.0
```

**Comment by abhishektiwari** [comment]
Similar fate for the `flask_dist_abc_def ` ran with Python `3.10.12`. `bobocep` installed via `pip`. Unable to runs examples.


```
bobocep 1.1.0
Flask 3.0.0
```

Similar error as last,

For `run_dist_1.py`
```
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:9091
Press CTRL+C to quit
[2023-10-02 22:22:36,866] ERROR in app: Exception on /data/str/a [GET]
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/x/Labs/joss/bobocep/tests/postman/flask_dist_abc_def/run_dist_1.py", line 28, in data_str
    engine.receiver.add_data(str(my_str))
NameError: name 'engine' is not defined
```

For `run_dist_2.py`

```
[2023-10-02 22:26:16,987] ERROR in app: Exception on /data/str/d [GET]
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/x/.pyenv/versions/3.10.12/envs/bobocep/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/x/Labs/joss/bobocep/tests/postman/flask_dist_abc_def/run_dist_2.py", line 28, in data_str
    engine.receiver.add_data(str(my_str))
NameError: name 'engine' is not defined
```

**Comment by abhishektiwari** [comment]
@r3w0p Please let me know if I am missing something.

**Comment by r3w0p** [comment]
Hello, thanks for raising an issue.

I have run these tests locally and can confirm that they work for me. I should provide more information for the Postman tests as to how they operate, because they are **not** to be executed in the same way as the unit tests in `tests_bobocep`.

In `postman/flask_123`, you need to directly run the `run.py` file. Failing to do this will mean that the code within `if __name__ == '__main__':` will not be executed. I suspect this is why you are getting the error `name 'engine' is not defined` because, indeed, `engine` is only defined within the aforementioned `if` statement!

- I personally use the PyCharm environment. If you are also using it, then you can right click `run.py` and press `Run 'run'`.
- Then, load up Postman and import the accompanying `.json` file, and then execute its GET requests. When I do this locally, I get, for example: `127.0.0.1 - - [03/Oct/2023 20:05:44] "GET /data/int/1 HTTP/1.1" 200 -`

Please let me know if you have tried the above. If it still doesn't work, then I will investigate further.

I will push some clearer notes on the Postman tests as soon as possible.

Alex.

**Comment by abhishektiwari** [comment]
Do these tests suppose to run inside the cloned repository?

I am installing `bobocep`, `flask`, and all other dependencies in an isolated virtual environment and executing the `run.py`. I believe that's how an actual user will consume `bobocep` – via a `pip` install. 

No issues with importing the Postman collections. 

I will give another shot and see if these runs in a cloned repository.

**Comment by r3w0p** [comment]
The Postman tests are for developer use only.

End users would `pip install bobocep` and would never be expected to run the Postman tests ever.

Running the tests requires the installation of requirements from both the `requirements.txt` and `requirements-dev.txt` files. If you have cloned `bobocep` locally, then you do not need to `pip install bobocep` as well.

Alex.

**Comment by r3w0p** [comment]
@abhishektiwari have you been able to resolve this problem? Shall I close the issue?

Alex.

**Comment by abhishektiwari** [comment]
Yes, it works now.

**Comment by abhishektiwari** [comment]
Closing it
